name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9.7"
      #
      # - name: Install pipenv
      #   run: |
      #     python -m pip install --upgrade pipenv
      #
      # - id: cache-pipenv
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      #
      # - name: Install dependencies
      #   if: steps.cache-pipenv.outputs.cache-hit != 'true'
      #   run: |
      #     pipenv install --deploy --dev
      #
      # - name: Run test
      #   run: |
      #     pipenv run python manage.py test
      #   env:
      #     DEBUG: true
      #     ALLOWED_HOSTS: localhost
      #     SECRET_KEY: 'change-secret-key'
      #     DB_ENGINE: django.db.backends.sqlite3
      #     DB_NAME: db.sqlite3
      #     TIME_ZONE: America/La_Paz
      #     LANGUAGE_CODE: es-ES

      - name: Deploy dev on heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_APIKEY }}
          heroku_app_name: "django-base-backend"
          heroku_email: "arteagamarcelo@gmail.com"
          usedocker: true
        env:
          HD_DEBUG: "true"
          HD_ALLOWED_HOSTS: "django-base-backend.herokuapp.com"
          HD_SECRET_KEY: "change-secret-key"
          HD_DB_ENGINE: "django.db.backends.sqlite3"
          HD_DB_NAME: "db.sqlite3"
          HD_TIME_ZONE: "America/La_Paz"
          HD_LANGUAGE_CODE: "es-ES"
          HD_DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          HD_DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          HD_DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}

      - name: Run migrations Django on heroku
        run: heroku run python manage.py migrate

      - name: Create superuser with ENV vars
        run: heroku run python manage.py createsuperuser --noinput
